version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: schemashift_postgres
    environment:
      POSTGRES_USER: sdet_admin
      POSTGRES_PASSWORD: SecretPassword123
      POSTGRES_DB: user_directory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
